import Link from "next/link";
import { ArrowRight, BarChart3, Bookmark, Brain, CheckCircle2, Clock3, Flame, Target } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { StatCard } from "@/components/stat-card";
import { createClient } from "@/lib/supabase/server";
import { getCurrentProfile } from "@/lib/auth";

interface Stats { attempted:number; correct:number; accuracy:number; bookmarks:number; due:number; sessions:number; recent:{day:string;attempted:number;correct:number}[]; subjects:{name:string;attempted:number;correct:number}[] }
export const metadata={title:"Dashboard"};
export default async function DashboardPage(){
 const profile=await getCurrentProfile(); const supabase=await createClient(); const {data}=await supabase.rpc("get_dashboard_stats");
 const stats=(data||{attempted:0,correct:0,accuracy:0,bookmarks:0,due:0,sessions:0,recent:[],subjects:[]}) as Stats;
 const maxRecent=Math.max(1,...stats.recent.map(x=>x.attempted));
 return <><PageHeading eyebrow="Overview" title={`Welcome back${profile?.display_name?`, ${profile.display_name.split(" ")[0]}`:""}`} description="Here is your revision picture. Keep sessions focused, review errors early and let consistency do the work." action={<Link className="btn btn-primary" href="/practice"><Brain size={18}/>Start practice</Link>}/>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Questions answered" value={stats.attempted} hint={`${stats.sessions} completed sessions`} icon={Target}/><StatCard label="Overall accuracy" value={`${Math.round(stats.accuracy*100)}%`} hint={`${stats.correct} correct answers`} icon={CheckCircle2}/><StatCard label="Due for review" value={stats.due} hint="Spaced repetition queue" icon={Clock3}/><StatCard label="Bookmarked" value={stats.bookmarks} hint="Saved for later" icon={Bookmark}/></div>
 <div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="card p-5 md:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Last seven days</h2><p className="mt-1 text-sm text-slate-500">Daily questions attempted</p></div><BarChart3 className="text-slate-400"/></div><div className="mt-8 flex h-48 items-end gap-3">{stats.recent.map((d)=><div key={d.day} className="flex flex-1 flex-col items-center gap-2"><div className="relative flex h-36 w-full items-end justify-center rounded-xl bg-slate-50"><div className="w-2/3 rounded-t-lg bg-[var(--primary)] transition-all" style={{height:`${Math.max(d.attempted?8:2,(d.attempted/maxRecent)*100)}%`}} title={`${d.attempted} attempted`}/></div><span className="text-[10px] font-bold text-slate-400">{new Date(d.day).toLocaleDateString("en-GB",{weekday:"short"})}</span></div>)}</div></section>
 <section className="card p-5 md:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Revision queue</h2><p className="mt-1 text-sm text-slate-500">Recommended next actions</p></div><Flame className="text-orange-500"/></div><div className="mt-5 space-y-3"><Link href="/review" className="flex items-center justify-between rounded-2xl border border-slate-100 p-4 hover:border-teal-200 hover:bg-teal-50/50"><div><p className="font-black">Review due questions</p><p className="mt-1 text-xs text-slate-500">{stats.due} waiting now</p></div><ArrowRight size={18}/></Link><Link href="/practice?status=incorrect" className="flex items-center justify-between rounded-2xl border border-slate-100 p-4 hover:border-violet-200 hover:bg-violet-50/50"><div><p className="font-black">Retry incorrect answers</p><p className="mt-1 text-xs text-slate-500">Target previous mistakes</p></div><ArrowRight size={18}/></Link><Link href="/practice?mode=exam" className="flex items-center justify-between rounded-2xl border border-slate-100 p-4 hover:border-orange-200 hover:bg-orange-50/50"><div><p className="font-black">Take a mock exam</p><p className="mt-1 text-xs text-slate-500">Feedback after completion</p></div><ArrowRight size={18}/></Link></div></section></div>
 <section className="card mt-5 p-5 md:p-6"><h2 className="text-lg font-black">Performance by subject</h2><p className="mt-1 text-sm text-slate-500">Accuracy in subjects you have attempted</p><div className="mt-5 grid gap-4 md:grid-cols-2">{stats.subjects.length?stats.subjects.map(s=>{const pct=s.attempted?Math.round(s.correct/s.attempted*100):0;return <div key={s.name}><div className="mb-2 flex justify-between text-sm"><span className="font-bold">{s.name}</span><span className="text-slate-500">{pct}% · {s.attempted}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[var(--primary)]" style={{width:`${pct}%`}}/></div></div>}):<p className="col-span-2 rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Subject analytics will appear after your first completed session.</p>}</div></section></>;
}
